[project]
name = "swjtu-auto-course-evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.18"
dependencies = [
    "bs4>=0.0.2",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
